

export const INC ="INC"
export const DEC ="DEC"

export const FETCH_TODO="FETCH_TODO"
export const FETCHED_TODO="FETCHED_TODO"
export const FETCHED_TODO_ERROR="FETCHED_TODO_ERROR"

export const FETCH_TODO_BY_ID="FETCH_TODO_BY_ID"
export const FETCHED_TODO_BY_ID="FETCHED_TODO_BY_ID"
export const FETCHED_TODO_BY_ID_ERROR="FETCHED_TODO_ERROR"

export const FETCH_COMMENTS="FETCH_COMMENTS"
export const FETCHED_COMMENTS="FETCHED_COMMENTS"



export const FETCH_DOG="FETCH_DOG"
export const FETCHED_DOG="FETCHED_DOG"