export const INC="INC"
export const DEC="DEC"
export const FETCH_TODO="FETCH_TODO"
export const FETCHED_TODO="FETCHED_TODO"
export const CAPTURE_ID = "CAPTURE_ID"
export const FETCH_TODO_ID="FETCH_TODO_ID"